<?xml version="1.0" encoding="utf-8"?><Database Name="EstudosCSharp" Class="ProdutosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HELDER\SQLEXPRESS;Initial Catalog=EstudosCSharp;Integrated Security=True" SettingsObjectName="EstudosCSharp.Properties.Settings" SettingsPropertyName="EstudosCSharpConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Produtos" Member="Produtos">
    <Type Name="Produto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Category" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>